# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My72MGB
email: ericsmgb@gmail.com
description: Here's a story of a lovely lady.
minimal_mistakes_skin: default
search: true
favicon: "https://my72mgb.com/favicon.png" # the favicon for your site
logo: &logo "https://my72mgb.com/favicon.png"
og_image: "https://my72mgb.com/assets/images/bio-photo.jpg"

# Build settings
markdown: kramdown
remote_theme: ehcloninger/modified-mistakes-skeleton
# theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

twitter:
  username: my1972mgb
  image: https://my72mgb.com/favicon.png

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Pearline White"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "That spiffy car you saw somewhere"
  twitter: "my1972mgb"
  instagram: "my72mgb"
  links:
    - label: "EricCloninger.com"
      icon: "fas fa-fw fa-link"
      url: https://EricCloninger.com"
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/my1972mgb"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram-square"
      url: "https://instagram.com/my72mgb"

github: [metadata]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      image:
        twitter: *logo
      twitter:
        card: summary
  - scope:
      path: "photos"
      type: pages
    values:
      layout: single
      author_profile: true
      image:
        twitter: *logo
      twitter:
        card: summary
        
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
